name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-material
      - run: pip install mkdocs-material-extensions
      - run: pip install mkdocs-simple-hooks
      - run: pip install mkdocs-video
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install mkdocs-minify-plugin
      - run: pip install mkdocs-static-i18n
      - run: pip install mkdocs-with-pdf
      - run: pip install qrcode
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-embed-external-markdown
      - run: pip install mkdocs-include-markdown-plugin
      - run: pip install mkdocs-ezlinks-plugin
      - run: pip install mkdocs-git-authors-plugin
      - run: pip install mkdocs-git-committers-plugin
      - run: pip install mkdocs-exclude
      - run: pip install pptx2md
      - run: pip install mkdocs-macros-plugin
      - run: mkdocs gh-deploy --force
